apiVersion: skaffold/v4beta5
kind: Config
build:
    artifacts:
        - image: pochunhuang1107/auth
          context: auth
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
          docker:
              dockerfile: Dockerfile
        - image: pochunhuang1107/client
          context: client
          sync:
              manual:
                  - src: '**/*.js'
                    dest: .
          docker:
              dockerfile: Dockerfile
        - image: pochunhuang1107/tickets
          context: tickets
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
          docker:
              dockerfile: Dockerfile
        - image: pochunhuang1107/orders
          context: orders
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
          docker:
              dockerfile: Dockerfile
        - image: pochunhuang1107/expiration
          context: expiration
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
          docker:
              dockerfile: Dockerfile
        - image: pochunhuang1107/payments
          context: payments
          sync:
              manual:
                  - src: 'src/**/*.ts'
                    dest: .
          docker:
              dockerfile: Dockerfile
    local:
        push: false
manifests:
    rawYaml:
        - ./infra/k8s/*
        - ./infra/k8s-dev/*
deploy:
    kubectl: {}
